start_alpha_a:
  ERL_AFLAGS="-name a@127.0.0.1 -setcookie cookiexyz" iex -S mix

start_alpha_b:
  ERL_AFLAGS="-name b@127.0.0.1 -setcookie cookiexyz" iex -S mix

start_alpha_c:
  ERL_AFLAGS="-name c@127.0.0.1 -setcookie cookiexyz" iex -S mix